### ISSUE TITLE
http_server sometimes couldn't fetch the png files

### ISSUE THREAD

**Issue by Amppa** [CaviarChen/Fog-of-World-Data-Parser#3]
## Problem:
Sometime, http_server couldn't fetch the png files

## Expected:
When browsing 127.0.0.1:8080/index.html, it should show OpenStreetMap and black path on it.

## Problem detail:
Tool has generated index.html, xxxx.png successfully
But sometimes, png didn't show up. I only saw a blank OpenStreetMap
The python http_server show fetch xxx.png: error 404. But the png file is locate at same directory as index.html

## Probability of this event:
50%

## Env:
Windows 10
browser: chrome, firefox, edge didn't help
shift+f5 didn't help, need to reboot the PC

## Solution:
Using a normal folder as output directory, instead of tmp_folder.
Then this issue didn't happen again.

I guess maybe there is a permission problem for Temp folder at Windows OS?

There is also an advantage to use a normal folder for output. The image can be cached. I've done that part.

**Comment by CaviarChen** [comment]
Hey, thanks for the super detailed report!
However, I am not going to fix this and I recommend you to avoid spending time on this project, becuase this is really only for demonstrating the data format and **I am going to archive this repo.**

**I am currently building a real [Fog of World] tool** and I have confidence in finishing the first version this week. So please stay tuned for that.
